arb-dir: lib/l10n
template-arb-file: intl_pt.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/generated/l10n
synthetic-package: false
preferred-supported-locales:
  - pt
  - en

